name: sandhai_admin
description: "Admin app for Sandhai – fruits & vegetables shop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  toastification: ^3.0.3

  # Navigation
  go_router: ^17.1.0

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # Backend
  supabase_flutter: ^2.12.0

  # Firebase
  firebase_core: ^4.5.0
  firebase_remote_config: ^6.2.0

  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

  # Utilities
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  package_info_plus: ^9.0.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.12.2
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter_gen:
  output: lib/assets/

flutter:
  uses-material-design: true
  assets:
    - env/