// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3DyZnqfKUMqlPXyjFFYjwuulExhAuuA',
    appId: '1:330361645157:web:ff7b8fbba684c23c2cfe8c',
    messagingSenderId: '330361645157',
    projectId: 'nm-ooty-vegetables',
    authDomain: 'nm-ooty-vegetables.firebaseapp.com',
    storageBucket: 'nm-ooty-vegetables.firebasestorage.app',
    measurementId: 'G-4ZVZJZNK2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEk9P5I6geLS_ij2pWiu8B6V4NrYEWDsM',
    appId: '1:330361645157:android:fb5da63c51b152e42cfe8c',
    messagingSenderId: '330361645157',
    projectId: 'nm-ooty-vegetables',
    storageBucket: 'nm-ooty-vegetables.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZOhUSL15aAQVxSnfnOEc80eX-3ZVePw',
    appId: '1:330361645157:ios:6d709186d26e4c012cfe8c',
    messagingSenderId: '330361645157',
    projectId: 'nm-ooty-vegetables',
    storageBucket: 'nm-ooty-vegetables.firebasestorage.app',
    iosBundleId: 'com.nmootyvegetables.sandhaiadmin.sandhaiAdmin',
  );
}
